export const PLANS = {
  "basic-growth-1m": {
    _id: "basic-growth-1m",
    title: "Basic Growth Plan (1 Month)",
    slug: "basic-growth-1m",
    description: "Essential visibility, menu setup, and ad optimization for 1 month.",
    currency: "INR",
    price: 9999,
    advancePrice: 9999,
    advanceText: "Pay ₹9,999",
    badge: "1 Month Plan",
    ctaText: "Choose Basic (1 Month)",
    isActive: true,
    whatsappSupportLink: "https://wa.me/918826073117",
  },
  "basic-growth-3m": {
    _id: "basic-growth-3m",
    title: "Basic Growth Plan (3 Months)",
    slug: "basic-growth-3m",
    description: "Essential visibility, menu setup, and ad optimization with 3-month savings.",
    currency: "INR",
    price: 23999,
    advancePrice: 23999,
    advanceText: "Pay ₹23,999",
    badge: "3 Months Plan",
    ctaText: "Choose Basic (3 Months)",
    isActive: true,
    whatsappSupportLink: "https://wa.me/918826073117",
  },
  "premium-growth-1m": {
    _id: "premium-growth-1m",
    title: "Premium Growth Plan (1 Month)",
    slug: "premium-growth-1m",
    description: "Advanced growth solution with branding, premium photography, repeat customer focus, and live rating calls.",
    currency: "INR",
    price: 14999,
    advancePrice: 14999,
    advanceText: "Pay ₹14,999",
    badge: "1 Month Plan",
    ctaText: "Choose Premium (1 Month)",
    isActive: true,
    whatsappSupportLink: "https://wa.me/918826073117",
  },
  "premium-growth-3m": {
    _id: "premium-growth-3m",
    title: "Premium Growth Plan (3 Months)",
    slug: "premium-growth-3m",
    description: "Full 90-day scale with branding, photography, live rating calls, and priority consultation.",
    currency: "INR",
    price: 35999,
    advancePrice: 35999,
    advanceText: "Pay ₹35,999",
    badge: "3 Months Plan",
    ctaText: "Choose Premium (3 Months)",
    isActive: true,
    whatsappSupportLink: "https://wa.me/918826073117",
  },
  "growth-consultation": {
    _id: "growth-consultation",
    title: "1-on-1 Growth Strategy Call (Google Meet)",
    slug: "growth-consultation",
    description: "30-min live Google Meet strategy session with a dedicated Zomato & Swiggy growth consultant.",
    currency: "INR",
    price: 0,
    advancePrice: 0,
    advanceText: "Free Strategy Call",
    badge: "Free Slot Booking",
    ctaText: "Book Meeting Now",
    features: [
      "30-Min Live Google Meet Consultation",
      "Full Zomato & Swiggy Menu Audit",
      "Ad Spend & ROAS Calculation",
      "Competitor Gap Analysis",
      "Actionable 30-Day Growth Roadmap"
    ],
    isActive: true,
    whatsappSupportLink: "https://wa.me/918826073117"
  }
};
